# REACTIONS

# List of particles can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# List of sounds can be found at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
# Use BLOCK_DUST as a particle if you want a blood effect

# Possible options for a reaction
#     messageToTarget: Message that the target will see
#     messageToSender: Message that the sender will see
#     particle: Particle that will be shown
#     sound: Sound that will be played
#     damageNum: How much damage the player will take when the reaction is used. Enter 0 for no damage or set damage to FALSE
# Not all options have to be used

reactions:
  kiss:
    messageToTarget: "%SENDER% has blown you a kiss ❤"
    messageToSender: "You just blew a kiss to %TARGET%. Awwww ❤"
    particle: "HEART"
    sound: "ENTITY_SLIME_JUMP"
  hug:
    messageToTarget:  "%SENDER% just sent you a warm hug."
    messageToSender: "You gave %TARGET% a warm hug."
    particle: "VILLAGER_HAPPY"
    sound: "ENTITY_VILLAGER_TRADE"
  pinch:
    messageToTarget: "&cYou were pinched by %SENDER%!"
    messageToSender: "&cYou just pinched %TARGET%"
    particle: "SNOWBALL"
    sound: "ENTITY_BAT_HURT"
    damageNum: 0.1
  punch:
    messageToTarget: "&c%SENDER% just punched you!"
    messageToSender: "&cYou punched %TARGET%!"
    particle: "CRIT_MAGIC"
    sound: "ENTITY_PLAYER_ATTACK_STRONG"
    damageNum: 0.1
  slap:
    messageToTarget: "&c%SENDER% slapped you!!!"
    messageToSender: "&cYou just slapped %TARGET%!"
    particle: "CRIT"
    sound: "ENTITY_PLAYER_ATTACK_STRONG"
    damageNum: 0.1
  stare:
    messageToTarget: "&4&o%SENDER% &c&ois staring at you..."
    messageToSender: "&4&oYou stare at %TARGET%..."
    particle: "PORTAL"
    sound: "ENTITY_ENDERMAN_STARE"
  lick:
    messageToTarget: "%SENDER% has licked you..."
    messageToSender: "You licked %TARGET%... did they taste good?"
    particle: "WATER_SPLASH"
    sound: "ENTITY_AXOLOTL_SPLASH"
  stab:
    messageToTarget: "&c%SENDER% has stabbed you!!!!"
    messageToSender: "&cYou stabbed %TARGET%!!!"
    particle: "BLOCK_DUST"
    sound: "ENTITY_PUFFER_FISH_STING"
    damageNum: 0.1
  pet:
    messageToTarget: "%SENDER% is petting you."
    messageToSender: "You are petting %TARGET%."
    particle: "VILLAGER_HAPPY"
    sound: "ENTITY_WOLF_AMBIENT"
  highfive:
    messageToTarget: "%SENDER% just gave you a highfive!"
    messageToSender: "You shared a highfive with %TARGET%!"
    particle: "CRIT"
    sound: "BLOCK_STONE_STEP"


#Config Version. NOT PLUGIN VERSION
ConfigVersion: 2.0


